services:
  hydrogen-storefront-vite:
    build:
      context: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=dev_secret
    command: npm run dev
